/**
 * División territorial administrativa — provincia de Alajuela (Costa Rica).
 * Cantones y distritos según DTA (referencia: INEC / TSE; listado verificado vía tabla pública tipo anexo provincial).
 */

export const PROVINCIA_ALAJUELA = 'Alajuela' as const

/** Los 16 cantones de la provincia de Alajuela */
export const CANTONES_PROVINCIA_ALAJUELA = [
  'Alajuela',
  'San Ramón',
  'Grecia',
  'San Mateo',
  'Atenas',
  'Naranjo',
  'Palmares',
  'Poás',
  'Orotina',
  'San Carlos',
  'Zarcero',
  'Sarchí',
  'Upala',
  'Los Chiles',
  'Guatuso',
  'Río Cuarto',
] as const

export type CantonAlajuela = (typeof CANTONES_PROVINCIA_ALAJUELA)[number]

export const DISTRITOS_POR_CANTON_ALAJUELA: Record<CantonAlajuela, readonly string[]> = {
  Alajuela: [
    'Alajuela',
    'San José',
    'Carrizal',
    'San Antonio',
    'Guácima',
    'San Isidro',
    'Sabanilla',
    'San Rafael',
    'Río Segundo',
    'Desamparados',
    'Turrúcares',
    'Tambor',
    'La Garita',
    'Sarapiquí',
  ],
  'San Ramón': [
    'San Ramón',
    'Santiago',
    'San Juan',
    'Piedades Norte',
    'Piedades Sur',
    'San Rafael',
    'San Isidro',
    'Ángeles',
    'Alfaro',
    'Volio',
    'Concepción',
    'Zapotal',
    'Peñas Blancas',
    'San Lorenzo',
  ],
  Grecia: ['Grecia', 'San Isidro', 'San José', 'San Roque', 'Tacares', 'Puente de Piedra', 'Bolívar'],
  'San Mateo': ['San Mateo', 'Desmonte', 'Jesús María', 'Labrador'],
  Atenas: ['Atenas', 'Jesús', 'Mercedes', 'San Isidro', 'Concepción', 'San José', 'Santa Eulalia', 'Escobal'],
  Naranjo: [
    'Naranjo',
    'San Miguel',
    'San José',
    'Cirrí Sur',
    'San Jerónimo',
    'San Juan',
    'El Rosario',
    'Palmitos',
  ],
  Palmares: ['Palmares', 'Zaragoza', 'Buenos Aires', 'Santiago', 'Candelaria', 'Esquipulas', 'La Granja'],
  Poás: ['San Pedro', 'San Juan', 'San Rafael', 'Carrillos', 'Sabana Redonda'],
  Orotina: ['Orotina', 'El Mastate', 'Hacienda Vieja', 'Coyolar', 'La Ceiba'],
  'San Carlos': [
    'Quesada',
    'Florencia',
    'Buenavista',
    'Aguas Zarcas',
    'Venecia',
    'Pital',
    'La Fortuna',
    'La Tigra',
    'La Palmera',
    'Venado',
    'Cutris',
    'Monterrey',
    'Pocosol',
  ],
  Zarcero: ['Zarcero', 'Laguna', 'Tapesco', 'Guadalupe', 'Palmira', 'Zapote', 'Brisas'],
  Sarchí: ['Sarchí Norte', 'Sarchí Sur', 'Toro Amarillo', 'San Pedro', 'Rodríguez'],
  Upala: [
    'Upala',
    'Aguas Claras',
    'San José (Pizote)',
    'Bijagua',
    'Delicias',
    'Dos Ríos',
    'Yolillal',
    'Canalete',
  ],
  'Los Chiles': ['Los Chiles', 'Caño Negro', 'El Amparo', 'San Jorge'],
  Guatuso: ['San Rafael', 'Buenavista', 'Cote', 'Katira'],
  'Río Cuarto': ['Río Cuarto', 'Santa Rita', 'Santa Isabel'],
}
